source "https://rubygems.org"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 8.0.2", ">= 8.0.2.1"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"
gem "tzinfo-data", platforms: %i[ windows jruby ]
gem "bootsnap", require: false

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"

  # Omakase Ruby styling [https://github.com/rails/rubocop-rails-omakase/]
  gem "rubocop-rails-omakase", require: false
  gem "rspec-rails"
  gem "annotaterb"
  gem "dotenv"
end

gem "sidekiq", "~> 8.0"
gem "sidekiq-cron", "~> 2.3"
gem "faraday", "~> 2.13"
gem "dry-rails", "~> 0.7.0"
gem "dry-transaction", "~> 0.16.0"
gem "redis", "~> 5.4"
gem "oj", "~> 3.16"
gem "nats-pure", "~> 2.5"
